[project]
name = "rddl"
version = "0.1.0"
description = "Reward Domain Description Language."
authors = [
    {name = "radoskov", email = "radoslav.skoviera@cvut.cz"},
]
dependencies = [
    "numpy>=1.26.4",
    "pytest>=8.1.1",
    "tqdm>=4.68.3",
    "pyyaml>=6.0.3",
    "sympy>=1.14.0",
    "networkx>=3.4.2",
    "pandas>=2.3.3",
    "memory-profiler>=0.61.0",
    "Levenshtein>=0.27.3",
    "multiprocess>=0.70.19",
    "typer>=0.12",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "BSDv3"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
# pythonpath = "tests/" "src/rddl/"

[tool.pdm]
distribution = true
